sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - CS_CHECK_DEPS="friendsofphp/php-cs-fixer:^2.9"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
      - DEPS=locked
      - EXECUTE_CS_CHECK=true
      - EXECUTE_TEST_SCRUTINIZER=true
    - php: 7.2
      env:
        - DEPS=latest
    - php: 7.3
      env:
      - DEPS=lowest
    - php: 7.3
      env:
      - DEPS=latest

  allow_failures:
  - php: 7.3

before_install:
  - if [[ $EXECUTE_TEST_SCRUTINIZER != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - if [[ "$DEPS" == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ "$DEPS" == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ "$EXECUTE_CS_CHECK" == 'tue' ]]; then composer require --dev $COMPOSER_ARGS $CS_CHECK_DEPS; fi

script:
  - if [[ "$EXECUTE_TEST_SCRUTINIZER" == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover coverage.clover ; fi
  - if [[ "$EXECUTE_TEST_SCRUTINIZER" != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ "$EXECUTE_CS_CHECK" == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run . ; fi

after_script:
  - if [[ "$EXECUTE_TEST_SCRUTINIZER" == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ "$EXECUTE_TEST_SCRUTINIZER" == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
